language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  
install:
  - pip install 'coverage<4'
  - pip install codecov

# Command to run tests
script: 
  - coverage run tests.py

# Run coverage.io
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov
