language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov

# Command to run tests
script: 
  - coverage run tests.py

# Run coverage.io
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov
